<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>25a8a261-d696-407b-a60b-35096c6b6577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rodo-alert__close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aada1ac4-c5de-4c73-88a6-8e77571ccba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rodo-alert__close</value>
      <webElementGuid>fb711ed4-a5af-4e40-8cc5-d003785c63e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>3248a464-2829-4d92-8c62-1401f6a9b551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;footer__background&quot;]/div[@class=&quot;rodo-alert&quot;]/div[@class=&quot;rodo-alert__close-wraper&quot;]/div[@class=&quot;rodo-alert__close&quot;]</value>
      <webElementGuid>ebf72b75-e2ab-4932-8d1a-4dc4e3e64721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5102c0a6-2d33-4ef4-a55b-88c052a8a9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rodo-alert__close</value>
      <webElementGuid>9f510f4c-e27d-453a-bd54-2c7e8485215c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>168bb525-a2dd-4d4b-8254-e414d87ced70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;footer__background&quot;]/div[@class=&quot;rodo-alert&quot;]/div[@class=&quot;rodo-alert__close-wraper&quot;]/div[@class=&quot;rodo-alert__close&quot;]</value>
      <webElementGuid>75c72936-8fed-49ee-a812-f4b46c12c805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa185f36-8a25-4144-bb6d-b04c83dd0bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rodo-alert__close</value>
      <webElementGuid>aa70ab59-d089-4560-a964-59793fcf07e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>1c3e0e12-fe42-4111-a698-4b23e6dda99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;footer__background&quot;]/div[@class=&quot;rodo-alert&quot;]/div[@class=&quot;rodo-alert__close-wraper&quot;]/div[@class=&quot;rodo-alert__close&quot;]</value>
      <webElementGuid>4e7f14c3-8de9-4ea8-b7ee-2765c575a150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc027bd9-6d5d-4914-bc6f-8a1c0099c2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rodo-alert__close</value>
      <webElementGuid>984b80ed-0bb6-4bc0-ba9b-3d274ac25be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>436d0920-2169-46e8-a33a-4bfec99dd65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;footer__background&quot;]/div[@class=&quot;rodo-alert&quot;]/div[@class=&quot;rodo-alert__close-wraper&quot;]/div[@class=&quot;rodo-alert__close&quot;]</value>
      <webElementGuid>19327a62-3aad-4cac-92f0-6c5abd293f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div[2]/div/div</value>
      <webElementGuid>d5deb22a-3a16-454d-a6ac-d9c9c5842e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Więcej...'])[1]/following::div[2]</value>
      <webElementGuid>4810d00d-a461-4f99-bd6d-65c1a082a72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wszelkie prawa zastrzeżone ©1991-2022 Biuro podróży Rainbow Tours S.A.'])[1]/following::div[3]</value>
      <webElementGuid>3a4ec374-0b87-47c5-b547-1a5c869545b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>12f62bde-7365-4c2a-aa4a-09ca8986b7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div</value>
      <webElementGuid>9cc7e6de-5754-405f-a47f-b49fdd838ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×' or . = '×')]</value>
      <webElementGuid>36efbf72-7b92-4539-97ae-3369996c505f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
