<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SZUKAJ</name>
   <tag></tag>
   <elementGuidId>6ca120f2-a3b0-484b-a6a3-82d47ea5aef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.filtry__search.r-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03eb6130-aabf-4190-aa88-a0486cf17d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/szukaj</value>
      <webElementGuid>fa96060e-196c-4286-ba6f-032bb30a00b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Szukaj</value>
      <webElementGuid>3fbd54c8-cde0-41bd-b381-2005c5ba366b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filtry__search r-button</value>
      <webElementGuid>c740f149-7230-49a6-9cae-2b64ecc56724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      SZUKAJ
    </value>
      <webElementGuid>ff57804f-f604-488d-80d1-c250099bfdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/header[@class=&quot;header-banner header-banner__webp&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry__element filtry__element--search&quot;]/a[@class=&quot;filtry__search r-button&quot;]</value>
      <webElementGuid>c4fb517a-222e-4f0a-8375-317996891cf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      <webElementGuid>c7eea372-524b-4bf1-9bf9-a487406cd96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SZUKAJ')]</value>
      <webElementGuid>eabe30a7-8deb-439e-9e14-66157ba7eb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samolot'])[1]/following::a[1]</value>
      <webElementGuid>34d5239e-66f2-40a7-98d4-5a5721074f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ Transportu'])[1]/following::a[1]</value>
      <webElementGuid>b3255c9b-ccd5-4f6a-b0aa-c37c0f1917c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biuro podróży Rainbow'])[1]/preceding::a[1]</value>
      <webElementGuid>201a3353-6a33-4a12-aa6d-68e81e1621ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wypoczynek • Grecja: Rodos'])[1]/preceding::a[4]</value>
      <webElementGuid>73de6d30-a507-4a78-b500-5802137a9a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SZUKAJ']/parent::*</value>
      <webElementGuid>9a02ef6f-aacb-4cb4-96d9-bd6989a453ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/szukaj')]</value>
      <webElementGuid>5d384a89-4e1b-4db7-a29f-21a5326dfe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/a</value>
      <webElementGuid>a2f4dc89-52b8-4ecb-a709-780404871345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/szukaj' and @title = 'Szukaj' and (text() = '
      SZUKAJ
    ' or . = '
      SZUKAJ
    ')]</value>
      <webElementGuid>20fe14fa-b210-4cf6-8e09-7e5b5d436cd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
