<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SZUKAJ (1)</name>
   <tag></tag>
   <elementGuidId>4161a39d-d2ad-476d-8668-6be9b9c6889a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.filtry__search.r-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>676d4f4a-af94-4544-883c-3d06a50e0818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/szukaj</value>
      <webElementGuid>b26ed7a2-0831-4389-b709-6952422eee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Szukaj</value>
      <webElementGuid>c2d91775-31d4-4244-b3c0-07a1b13f6640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filtry__search r-button</value>
      <webElementGuid>83cbc141-fd98-4cd9-995e-0c287ce0fa92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      SZUKAJ
    </value>
      <webElementGuid>9bea19c7-bb26-4fa7-97ce-7d7ea6696f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;strona-glowna&quot;]/header[@class=&quot;header-banner header-banner__webp&quot;]/div[@class=&quot;wrap wrap-header&quot;]/div[@class=&quot;filtry filtry&quot;]/div[@class=&quot;filtry__element filtry__element--search&quot;]/a[@class=&quot;filtry__search r-button&quot;]</value>
      <webElementGuid>857cc8ba-a507-45a9-8ad6-65f5ba3312b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/header/div/div/div[6]/a</value>
      <webElementGuid>863fcb61-0e70-4d7a-b49d-79ef9a23a6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SZUKAJ')]</value>
      <webElementGuid>e5cd3f58-28cb-470b-b5f4-f60136a40367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samolot'])[1]/following::a[1]</value>
      <webElementGuid>555c3851-28b4-43e7-9904-7efdffb211d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ Transportu'])[1]/following::a[1]</value>
      <webElementGuid>39368026-c019-490a-bd5d-a24d04cc8057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biuro podróży Rainbow'])[1]/preceding::a[1]</value>
      <webElementGuid>0f37c103-7a4b-447e-8c5f-00c715ac3b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wypoczynek • Grecja: Rodos'])[1]/preceding::a[4]</value>
      <webElementGuid>8b4f9f05-3f47-4c85-b46d-239ea2907d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SZUKAJ']/parent::*</value>
      <webElementGuid>d8efb141-7166-4f0e-80d0-69b6bc6b3a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/szukaj')]</value>
      <webElementGuid>771c0443-f0c4-44d2-959a-6b38e1c2cded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/a</value>
      <webElementGuid>822910a8-055c-4c43-ae6d-2ef1eaec23c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/szukaj' and @title = 'Szukaj' and (text() = '
      SZUKAJ
    ' or . = '
      SZUKAJ
    ')]</value>
      <webElementGuid>23b96dcd-af21-4f44-b8c7-fd4b2cc77bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
