<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Karolina, Warszawa, 2021.09.14_seo-long_662b8a</name>
   <tag></tag>
   <elementGuidId>81f1b3b0-7fe4-4510-9524-bc20d66d88f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[2]/div/div/div/div[3]/div/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87abc823-099b-44d9-b8a9-63210e1357b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-long__swiper--arrow right</value>
      <webElementGuid>e25ad7a3-d5ef-4b74-ac81-8d3860291612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/section[@class=&quot;section blue-Gradient&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;seo-long__container background&quot;]/div[@class=&quot;seo-long__container--row&quot;]/div[@class=&quot;seo-long__container--col&quot;]/div[@class=&quot;swiper-r&quot;]/div[@class=&quot;seo-long__swiper--arrow right&quot;]</value>
      <webElementGuid>a2942782-79b1-4ac6-aa23-8c51e2a0a8d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[2]/div/div/div/div[3]/div/div[2]/div[3]</value>
      <webElementGuid>d5f05980-d671-4cba-9133-269334d110a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karolina, Warszawa, 2021.09.14'])[1]/following::div[1]</value>
      <webElementGuid>a66b5f3b-0bb9-48ac-9823-7887d4d6d65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dodał(a):'])[10]/following::div[1]</value>
      <webElementGuid>463fe22b-ea0b-4b90-a7c0-5b69ab8a5760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call center'])[1]/preceding::div[7]</value>
      <webElementGuid>3e189f6d-c49f-4666-bd07-59ba38260692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mail'])[1]/preceding::div[9]</value>
      <webElementGuid>61b98787-358e-4f4c-ad0d-6a96a8c73c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div[2]/div[3]</value>
      <webElementGuid>ba6052fe-908d-4384-8e26-e360ee545c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
