<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cena_r-input range-input__input filled</name>
   <tag></tag>
   <elementGuidId>ed3c833f-a662-4f8c-93c3-a463ee2c5cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.r-input.range-input__input.filled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4885906-17e9-408b-a727-d49545461be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>128ea684-1a3a-4129-9c75-e5cd5f8b2ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>od</value>
      <webElementGuid>88af8fce-f313-4624-9f75-7569f5d20f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r-input range-input__input filled</value>
      <webElementGuid>7232e0e0-a721-41e5-9c22-f2f4c869b4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/section[@class=&quot;section no-padding&quot;]/div[@class=&quot;wrap szukaj-wrap&quot;]/aside[@class=&quot;sidebar&quot;]/div[@class=&quot;side-filters&quot;]/div[@class=&quot;side-filters__filter&quot;]/section[@class=&quot;filter-section radio-filter&quot;]/div[@class=&quot;filter-section__content&quot;]/div[@class=&quot;range-input side-filters__range-input top&quot;]/div[@class=&quot;range-input__input-wrap&quot;]/input[@class=&quot;r-input range-input__input filled&quot;]</value>
      <webElementGuid>f28583fa-e33d-4abc-8ddb-8cf23ad8ee24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[3]</value>
      <webElementGuid>ef9f7d71-265d-46bd-b84a-87b4e80510c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section/div/aside/div[3]/div[4]/section/div[2]/div/div/input</value>
      <webElementGuid>ed8f536a-0745-43b5-807c-73a0a9b22cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/section/div[2]/div/div/input</value>
      <webElementGuid>edf292cb-39d7-4db2-971f-e98d004e1bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'od']</value>
      <webElementGuid>af8e361b-629a-478f-9c69-e3ae2e20c79a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
