<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dlaczego warto wyjecha do Grecji</name>
   <tag></tag>
   <elementGuidId>ed3054d9-6240-4313-a901-bb535c689151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/main/section[2]/div/div/div/div/div[2]/div/ul/li/h2/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.accordion__text--head-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>624044f4-959b-48ab-b083-ef11023f109a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion__text--head-line</value>
      <webElementGuid>2ad9e600-7ded-446c-8bcf-6f6b24837585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dlaczego warto wyjechać do Grecji?</value>
      <webElementGuid>25743d69-c7eb-4b59-b765-c9d946465fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;default-layout__content&quot;]/main[@class=&quot;szukaj&quot;]/section[@class=&quot;section blue-Gradient&quot;]/div[@class=&quot;wrap&quot;]/div[1]/div[@class=&quot;seo-long__container background&quot;]/div[@class=&quot;seo-long__container--row&quot;]/div[@class=&quot;seo-long__container--col w56&quot;]/div[@class=&quot;accordion-seo__container&quot;]/ul[@class=&quot;accordion__list&quot;]/li[@class=&quot;accordion__list--item&quot;]/h2[@class=&quot;accordion__text--head&quot;]/span[@class=&quot;accordion__text--head-line&quot;]</value>
      <webElementGuid>34b282bf-e242-41a3-a9e3-95a4a366fad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/main/section[2]/div/div/div/div/div[2]/div/ul/li/h2/span</value>
      <webElementGuid>f40b1950-5c99-4f65-837d-579969fa5945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Minute'])[2]/following::span[1]</value>
      <webElementGuid>282e6c6b-8f87-4d22-a624-f499726d5e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Inclusive'])[1]/following::span[1]</value>
      <webElementGuid>fb987268-14e5-4c77-ae54-c15cf6d53003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Co warto wiedzieć przed podróżą do Grecji – praktyczny przewodnik'])[1]/preceding::span[3]</value>
      <webElementGuid>dad04fe6-b4b2-48d6-bd1e-2c9cf0c8f604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Walutą obowiązującą w Grecji jest euro.'])[1]/preceding::span[6]</value>
      <webElementGuid>f1fd5122-0ca6-4828-95a4-50d06e57aad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dlaczego warto wyjechać do Grecji?']/parent::*</value>
      <webElementGuid>a0c59d21-3743-451f-9f3c-f0783f808be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>c78bae71-2d6d-4197-b611-fd18468de564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dlaczego warto wyjechać do Grecji?' or . = 'Dlaczego warto wyjechać do Grecji?')]</value>
      <webElementGuid>6771e99f-3d73-487d-9129-8ef717e34d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
