<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Oferta_mobile__header-rainbow</name>
   <tag></tag>
   <elementGuidId>aac3439b-9728-45f5-b3e3-fc2d0ef1a3e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainHeader']/div/div/header/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mobile__header-rainbow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8f4e6a79-806e-4f5b-849c-4a14f3a9bdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images2.r.pl/r-pl/nowe-menu-gorne/napis.svg</value>
      <webElementGuid>290a2025-abea-4620-81d7-9da11136c4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>napis-rainbow</value>
      <webElementGuid>3335c716-9e95-414f-963f-27d959920211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile__header-rainbow</value>
      <webElementGuid>6e63d848-c580-46c3-809a-8a1b7e48f707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainHeader&quot;)/div[@class=&quot;header__desktop&quot;]/div[@class=&quot;desktop__header-position&quot;]/header[@class=&quot;desktop__container-position&quot;]/div[1]/a[@class=&quot;footer-men__siteMap__link&quot;]/div[@class=&quot;desktop__header-rpl&quot;]/img[@class=&quot;mobile__header-rainbow&quot;]</value>
      <webElementGuid>2d2c8f43-54fa-4e14-8376-279505fc8248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainHeader']/div/div/header/div/a/div/img</value>
      <webElementGuid>c0b2d51f-8bef-4197-91b3-3c2ab6287e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='napis-rainbow']</value>
      <webElementGuid>69ec613b-e2d7-4ab8-8aa0-ad4ab9000cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>1b2192f3-65bc-49f2-aac5-79d86ee495a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images2.r.pl/r-pl/nowe-menu-gorne/napis.svg' and @alt = 'napis-rainbow']</value>
      <webElementGuid>986e7e0c-6539-44ca-9a5e-4336cfdc4e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
